
import React, { useState } from 'react';
import type { ReportData, Recipient } from '../types';
import { BackIcon, CheckIcon, CopyIcon, RedoIcon, EmailIcon } from './icons';

interface ReportScreenProps {
  reportData: ReportData | null;
  recipients: Recipient[] | null;
  onBackToChat: () => void;
  onStartOver: () => void;
}

// Email draft display component
const EmailDraft: React.FC<{ subject: string; body: string }> = ({ subject, body }) => (
  <div className="bg-slate-800/50 border rounded-lg shadow-lg border-slate-700 p-8 mb-8">
    <h2 className="text-2xl font-bold text-slate-100 mb-2">Email Draft</h2>
    <div className="mb-4">
      <span className="text-sm font-semibold text-slate-400">Subject:</span>
      <span className="ml-2 text-base text-slate-300">{subject}</span>
    </div>
    <div>
      <span className="text-sm font-semibold text-slate-400">Body:</span>
      <pre className="mt-1 text-base text-slate-300 whitespace-pre-wrap bg-slate-900/40 p-4 rounded-md">{body}</pre>
    </div>
  </div>
);

const ReportScreen: React.FC<ReportScreenProps> = ({ reportData, recipients, onBackToChat, onStartOver }) => {
  const [copied, setCopied] = useState(false);

  if (!reportData || !recipients) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-4 text-center">
        <h2 className="text-2xl font-bold">Could not generate report.</h2>
        <p className="mt-2 text-slate-400">Something went wrong. Please go back and try again.</p>
        <button
          onClick={onBackToChat}
          className="flex items-center gap-2 px-4 py-2 mt-6 text-sm font-medium text-white transition-colors duration-200 bg-sky-600 rounded-md hover:bg-sky-700"
        >
          <BackIcon />
          <span>Back to Chat</span>
        </button>
      </div>
    );
  }

  const formatReportForCopy = () => {
    return [
      'INCIDENT REPORT',
      '--------------------------------------',
      `Date and Time of Incident:\n${reportData.date}`,
      `Location of Incident:\n${reportData.location}`,
      `Individuals Involved:\n${reportData.involved}`,
      `Detailed Description of Events:\n${reportData.description}`,
      `Impact:\n${reportData.impact}`,
      '--------------------------------------',
      'Generated by Safe Harbor AI'
    ].join('\n\n');
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(formatReportForCopy());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // When a recipient is clicked, open mailto with their email, subject, and body
  const handleRecipientClick = (recipient: Recipient) => {
    const subject = "Incident Report Draft";
    const body = formatReportForCopy();
    const mailtoLink = `mailto:${recipient.email || ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="max-w-4xl p-4 mx-auto my-8 bg-slate-900/50 backdrop-blur-sm md:p-8">
      <EmailDraft subject="Incident Report Draft" body={formatReportForCopy()} />
      <div className="flex gap-2 mb-8">
        <button
          onClick={handleCopyToClipboard}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white transition-colors duration-200 rounded-md bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:ring-offset-slate-800"
        >
          {copied ? <CheckIcon /> : <CopyIcon />}
          <span>{copied ? 'Copied!' : 'Copy Text'}</span>
        </button>
      </div>
      <div className="p-8 bg-slate-800/50 border rounded-lg shadow-lg border-slate-700">
        <h2 className="text-2xl font-bold text-slate-100">Suggested Recipients</h2>
        <p className="mt-2 text-sm text-slate-400">
          Depending on your situation, you might consider sharing this report with one of the following. This is not exhaustive and is not legal advice.
        </p>
        <ul className="mt-6 space-y-4">
          {recipients.map((recipient, index) => (
            <li key={index} className="p-4 border rounded-md bg-slate-700/50 border-slate-700 hover:bg-sky-800/40 cursor-pointer transition" onClick={() => handleRecipientClick(recipient)}>
              <div className="flex flex-col md:flex-row md:items-center md:justify-between">
                <div>
                  <h3 className="font-semibold text-sky-400">{recipient.name}</h3>
                  <p className="mt-1 text-sm text-slate-300">{recipient.description}</p>
                </div>
                {recipient.email && (
                  <span className="mt-2 md:mt-0 text-xs text-slate-400">{recipient.email}</span>
                )}
              </div>
            </li>
          ))}
        </ul>
      </div>
      <div className="flex flex-col gap-4 mt-8 md:flex-row">
        <button onClick={onBackToChat} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 border rounded-md shadow-sm text-slate-200 bg-slate-700 border-slate-600 hover:bg-slate-600">
          <BackIcon />
          <span>Back to Chat</span>
        </button>
        <button onClick={onStartOver} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 bg-red-900/40 border border-red-800/60 rounded-md shadow-sm text-red-300 hover:bg-red-900/60">
          <RedoIcon />
          <span>Start New Session</span>
        </button>
      </div>
    </div>
  );
};

export default ReportScreen;